import { connect } from 'cloudflare:sockets';
let userID='你的UUID';
let proxyIP='你的PROXYIP';
function a(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
if(!a(userID))throw new Error('uuid err');
export default {async fetch(b,c,d){try{userID=c.UUID||userID;proxyIP=c.PROXYIP||proxyIP;let e=b.headers.get('Upgrade');if(!e||e!=='websocket'){return new Response('cloudflare',{status:200,headers:{'content-type':'text/plain;charset=utf-8'}})}return await f(b)}catch(g){return new Response(String(g))}}};
async function f(h){const i=new WebSocketPair();const[j,k]=Object.values(i);k.accept();let l='';let m='';const n=(o,p)=>console.log('['+l+':'+m+'] '+o,p||'');const q=h.headers.get('sec-websocket-protocol')||'';const r=s(k,q,n);let t={value:null};let u=null;let v=false;r.pipeTo(new WritableStream({async write(w){if(v&&u)return u(w);if(t.value){const x=t.value.writable.getWriter();await x.write(w);x.releaseLock();return;}const y=z(w,userID);if(y.hasError)throw new Error(y.message);l=y.addressRemote;m=String(y.portRemote);if(y.isUDP){if(y.portRemote!==53)throw new Error('udp only 53');v=true;}const A=new Uint8Array([y.vlessVersion[0],0]);const B=w.slice(y.rawDataIndex);if(v){const C=await aa(k,A,n);u=C.write;u(B);return;}ab(t,y.addressRemote,y.portRemote,B,k,A,n)}})).catch(err=>n('pipe err',err));return new Response(null,{status:101,webSocket:j})}
function s(c,d,e){let f=false;return new ReadableStream({start(g){c.addEventListener('message',h=>{if(!f)g.enqueue(h.data)});c.addEventListener('close',()=>{ac(c);if(!f)g.close()});c.addEventListener('error',h=>g.error(h));const i=ad(d);if(i.error)g.error(i.error);else if(i.earlyData)g.enqueue(i.earlyData)},cancel(g){f=true;ac(c)}})}
function z(a1,a2){if(a1.byteLength<24)return{hasError:true,message:'bad'};const a3=new Uint8Array(a1.slice(0,1));if(ae(new Uint8Array(a1.slice(1,17)))!==a2)return{hasError:true,message:'invalid user'};const a4=new Uint8Array(a1.slice(17,18))[0];const a5=new Uint8Array(a1.slice(18+a4,19+a4))[0];let a6=a5===2;if(a5!==1&&a5!==2)return{hasError:true,message:'cmd'};const a7=18+a4+1;const a8=new DataView(a1.slice(a7,a7+2)).getUint16(0);let a9=a7+2;const b1=new Uint8Array(a1.slice(a9,a9+1))[0];let b2='';let b3=a9+1;let b4=0;if(b1===1){b4=4;b2=new Uint8Array(a1.slice(b3,b3+4)).join('.')}else if(b1===2){b4=new Uint8Array(a1.slice(b3,b3+1))[0];b3++;b2=new TextDecoder().decode(a1.slice(b3,b3+b4))}else{return{hasError:true,message:'atype'}};return{hasError:false,addressRemote:b2,portRemote:a8,rawDataIndex:b3+b4,vlessVersion:a3,isUDP:a6}}
async function ab(c,d,e,f,g,h,i){async function j(k,l){const m=connect({hostname:k,port:l});c.value=m;const n=m.writable.getWriter();await n.write(f);n.releaseLock();return m}const o=await j(d,e);af(o,g,h,async()=>{const p=await j(proxyIP||d,e);af(p,g,h,null,i)},i)}
async function af(a,b,c,d,e){let f=c;let g=false;await a.readable.pipeTo(new WritableStream({async write(h,i){g=true;if(b.readyState!==1)i.error('ws');if(f){b.send(await new Blob([f,h]).arrayBuffer());f=null}else b.send(h)}})).catch(()=>ac(b));if(!g&&d)await d()}
function ad(a){if(!a)return{error:null};try{a=a.replace(/-/g,'+').replace(/_/g,'/');const b=atob(a);const c=Uint8Array.from(b,d=>d.charCodeAt(0));return{earlyData:c.buffer,error:null}}catch(e){return{error:e}}}
function ac(a){try{if(a.readyState===1||a.readyState===2)a.close()}catch(b){}}
const ag=[];for(let i=0;i<256;i++)ag.push((i+256).toString(16).slice(1));function ae(a,b=0){const c=(x)=>ag[a[b+x]];return(c(0)+c(1)+c(2)+c(3)+'-'+c(4)+c(5)+'-'+c(6)+c(7)+'-'+c(8)+c(9)+'-'+c(10)+c(11)+c(12)+c(13)+c(14)+c(15)).toLowerCase()}
async function aa(a,b,c){let d=false;const e=new TransformStream({transform(f,g){for(let h=0;h<f.byteLength;){const i=new DataView(f.slice(h,h+2)).getUint16(0);g.enqueue(new Uint8Array(f.slice(h+2,h+2+i)));h=h+2+i}}});e.readable.pipeTo(new WritableStream({async write(f){const g=await fetch('https://1.1.1.1/dns-query',{method:'POST',headers:{'content-type':'application/dns-message'},body:f});const h=await g.arrayBuffer();const i=h.byteLength;const j=new Uint8Array([(i>>8)&255,i&255]);if(a.readyState===1){if(d)a.send(await new Blob([j,h]).arrayBuffer());else{a.send(await new Blob([b,j,h]).arrayBuffer());d=true}}}}));const k=e.writable.getWriter();return{write(l){k.write(l)}}}
